(function(g){var window=this;var TAa=function(a,b){return g.Tb(a,b)},P6=function(a){g.Am(a,"zx",g.xb());
return a},Q6=function(a,b,c){g.za(c)||(c=[String(c)]);
g.Dm(a.g,b,c)},UAa=function(a,b){var c=[];
g.nk(b,function(a){try{var b=g.$C.prototype.l.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.ZC(b)&&c.push(a):c.push(a)},a);
return c},VAa=function(a,b){var c=UAa(a,b);
(0,g.B)(c,function(a){g.$C.prototype.remove.call(this,a)},a)},WAa=function(a){if(a.yd){if(a.yd.locationOverrideToken)return{locationOverrideToken:a.yd.locationOverrideToken};
if(null!=a.yd.latitudeE7&&null!=a.yd.longitudeE7)return{latitudeE7:a.yd.latitudeE7,longitudeE7:a.yd.longitudeE7}}return null},XAa=function(a,b,c,d){var e=new g.rm(null,void 0);
a&&g.sm(e,a);b&&g.tm(e,b);c&&g.um(e,c);d&&g.vm(e,d);return e},YAa=function(a){g.PF[a]&&(a=g.PF[a],(0,g.B)(a,function(a){g.NF[a]&&delete g.NF[a]}),a.length=0)},ZAa=function(a){var b=g.MF();
if(b)if(b.clear(a),a)YAa(a);else for(var c in g.PF)YAa(c)},R6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.o=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.lm;this.g=this.l="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",$Aa(this,a.capabilities||""),aBa(this,a.experiments||""),this.l=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},$Aa=function(a,b){a.capabilities.clear();
(0,g.Kd)(b.split(","),g.Fa(TAa,bBa)).forEach(function(b){a.capabilities.add(b)})},aBa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},S6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},T6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},cBa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},dBa=function(a){return new S6(a)},eBa=function(a){return g.za(a)?(0,g.G)(a,dBa):[]},U6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},V6=function(a){return g.za(a)?"["+(0,g.G)(a,U6).join(",")+"]":"null"},W6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},fBa=function(a){return(0,g.G)(a,function(a){return{key:a.id,
name:a.name}})},X6=function(a,b){return g.La(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},Y6=function(a,b){return g.La(a,function(a){return T6(a,b)})},gBa=function(){var a=(0,g.IG)();
a&&VAa(a,a.g.Pd(!0))},Z6=function(){var a=g.LG("yt-remote-connected-devices")||[];
g.gb(a);return a},hBa=function(a){if(g.Qa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.G)(a,function(a,b){return 0==b?a:a.substring(c.length)})},iBa=function(a){g.KG("yt-remote-connected-devices",a,86400)},a7=function(){if($6)return $6;
var a=g.LG("yt-remote-device-id");a||(a=W6(),g.KG("yt-remote-device-id",a,31536E3));for(var b=Z6(),c=1,d=a;g.Pa(b,d);)c++,d=a+"#"+c;return $6=d},b7=function(){var a=Z6(),b=a7();
g.Pa(a,b);g.NG()&&g.jb(a,b);a=hBa(a);if(g.Qa(a))try{g.vG("remote_sid")}catch(c){}else try{g.uG("remote_sid",a.join(","),-1)}catch(c){}},jBa=function(){return g.LG("yt-remote-session-browser-channel")},kBa=function(){return g.LG("yt-remote-local-screens")||[]},lBa=function(){g.KG("yt-remote-lounge-token-expiration",!0,86400)},mBa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.G)(kBa(),function(a){return a.loungeToken}),c=(0,g.G)(a,function(a){return a.loungeToken});
(0,g.$l)(c,function(a){return!g.Pa(b,a)})&&lBa();
g.KG("yt-remote-local-screens",a,31536E3)},nBa=function(a,b){g.KG("yt-remote-session-browser-channel",a);
g.KG("yt-remote-session-screen-id",b);var c=Z6(),d=a7();g.Pa(c,d)||c.push(d);iBa(c);b7()},c7=function(a){a||(g.MG("yt-remote-session-screen-id"),g.MG("yt-remote-session-video-id"));
b7();a=Z6();g.Ua(a,a7());iBa(a)},oBa=function(){if(!d7){var a=g.kD();
a&&(d7=new g.UC(a))}return d7?!!d7.get("yt-remote-use-staging-server"):!1},pBa=function(){var a=window.document.createElement("a");
g.Zc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Bb(a)},qBa=function(a,b){var c=g.Dd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.ad(c,g.be("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},rBa=function(){var a=pBa(),b=window.document.getElementById(a),c=b&&g.YE(b,"loaded");
c||b&&!c||(b=qBa(a,function(){g.YE(b,"loaded")||(g.XE(b,"loaded","true"),g.TF(a),g.TD(g.Fa(ZAa,a),0))}))},e7=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},sBa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},f7=function(a){a.length?tBa(a.shift(),function(){f7(a)}):g7()},uBa=function(a){return"chrome-extension://"+a+h7},tBa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},i7=function(a){return 0<=window.navigator.userAgent.indexOf(a)},g7=function(){var a=sBa();
a&&a(!1,"No cast extension found")},j7=function(){if(vBa){var a=2,b=sBa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;tBa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",g7,c)}},wBa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(j7(),a({command:"cast.sender.init"}))},xBa=function(){j7();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);f7(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+h7,"//www.gstatic.com/eureka/clank"+h7])},k7=function(a,b,c){g.M.call(this);
this.C=null!=c?(0,g.z)(a,c):a;this.od=b;this.B=(0,g.z)(this.sJ,this);this.g=!1;this.l=0;this.o=this.Ba=null;this.A=[]},l7=function(){},m7=function(a,b,c,d){this.g=a;
this.o=b;this.D=c;this.C=d||1;this.A=45E3;this.W=new g.Hm(this);this.l=new g.rg;this.l.setInterval(250)},zBa=function(a,b,c){a.Jj=1;
a.hh=P6(b.clone());a.Ni=c;a.B=!0;yBa(a,null)},n7=function(a,b,c,d,e){a.Jj=1;
a.hh=P6(b.clone());a.Ni=null;a.B=c;e&&(a.FD=!1);yBa(a,d)},yBa=function(a,b){a.wk=(0,g.F)();
o7(a);a.Gh=a.hh.clone();Q6(a.Gh,"t",a.C);a.Km=0;a.Pc=a.g.xr(a.g.Bm()?b:null);0<a.es&&(a.Fp=new g.Rk((0,g.z)(a.UE,a,a.Pc),a.es));a.W.U(a.Pc,"readystatechange",a.OU);var c=a.ki?g.ac(a.ki):{};a.Ni?(a.qq="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Pc.send(a.Gh,a.qq,a.Ni,c)):(a.qq="GET",a.FD&&!g.zd&&(c.Connection="close"),a.Pc.send(a.Gh,a.qq,null,c));a.g.wf(1)},CBa=function(a,b,c){for(var d=!0;!a.Uh&&a.Km<c.length;){var e=ABa(a,c);
if(e==p7){4==b&&(a.ih=4,q7(15),d=!1);break}else if(e==BBa){a.ih=4;q7(16);d=!1;break}else r7(a,e)}4==b&&0==c.length&&(a.ih=1,q7(17),d=!1);a.Cf=a.Cf&&d;d||(s7(a),t7(a))},ABa=function(a,b){var c=a.Km,d=b.indexOf("\n",c);
if(-1==d)return p7;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return BBa;d+=1;if(d+c>b.length)return p7;var e=b.substr(d,c);a.Km=d+c;return e},EBa=function(a,b){a.wk=(0,g.F)();
o7(a);var c=b?window.location.hostname:"";a.Gh=a.hh.clone();g.Am(a.Gh,"DOMAIN",c);g.Am(a.Gh,"t",a.C);try{a.Df=new window.ActiveXObject("htmlfile")}catch(n){s7(a);a.ih=7;q7(22);t7(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in u7)k=u7[l];else if(l in DBa)k=u7[l]=DBa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=u7[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.bd(g.wc("b/12014412"),d);a.Df.open();a.Df.write(g.Tc(c));a.Df.close();a.Df.parentWindow.m=(0,g.z)(a.VT,a);a.Df.parentWindow.d=(0,g.z)(a.RC,a,!0);a.Df.parentWindow.rpcClose=(0,g.z)(a.RC,a,!1);c=a.Df.createElement("DIV");a.Df.parentWindow.document.body.appendChild(c);d=g.Kc(a.Gh.toString());d=g.qb(g.Hc(d));d=g.bd(g.wc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.Tc(d);
a.g.wf(1)},o7=function(a){a.Ov=(0,g.F)()+a.A;
FBa(a,a.A)},FBa=function(a,b){if(null!=a.Mk)throw Error("WatchDog timer not null");
a.Mk=v7((0,g.z)(a.nU,a),b)},w7=function(a){a.Mk&&(g.w.clearTimeout(a.Mk),a.Mk=null)},t7=function(a){a.g.Zy()||a.Uh||a.g.rp(a)},s7=function(a){w7(a);
g.$e(a.Fp);a.Fp=null;a.l.stop();g.Nm(a.W);if(a.Pc){var b=a.Pc;a.Pc=null;b.abort();b.dispose()}a.Df&&(a.Df=null)},r7=function(a,b){try{a.g.KC(a,b),a.g.wf(4)}catch(c){}},HBa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;GBa(a,b,function(e){e?c(!0):g.w.setTimeout(function(){HBa(a,b,c,d,f)},f)})}},GBa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{x7(d),c(!0)}catch(e){}};
d.onerror=function(){try{x7(d),c(!1)}catch(e){}};
d.onabort=function(){try{x7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{x7(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},x7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},IBa=function(a){this.g=a;
this.l=new l7},JBa=function(a){var b=y7(a.g,a.Tk,"/mail/images/cleardot.gif");
P6(b);HBa(b.toString(),5E3,(0,g.z)(a.DI,a),3,2E3);a.wf(1)},A7=function(a){var b=a.g.H;
if(null!=b)q7(5),b?(q7(11),z7(a.g,a,!1)):(q7(12),z7(a.g,a,!0));else if(a.re=new m7(a,void 0,void 0,void 0),a.re.ki=a.Zr,b=a.g,b=y7(b,b.Bm()?a.yl:null,a.ds),q7(5),!g.xd||g.qc(10))Q6(b,"TYPE","xmlhttp"),n7(a.re,b,!1,a.yl,!1);else{Q6(b,"TYPE","html");var c=a.re;a=!!a.yl;c.Jj=3;c.hh=P6(b.clone());EBa(c,a)}},B7=function(a,b,c){this.g=1;
this.l=[];this.A=[];this.B=new l7;this.F=a||null;this.H=null!=b?b:null;this.C=c||!1},KBa=function(a,b){this.g=a;
this.map=b;this.context=null},LBa=function(a){g.bf.call(this,"statevent",a)},MBa=function(a,b){g.bf.call(this,"timingevent",a);
this.size=b},NBa=function(a){g.bf.call(this,"serverreachability",a)},QBa=function(a){OBa(a);
if(3==a.g){var b=a.gm++,c=a.bo.clone();g.Am(c,"SID",a.o);g.Am(c,"RID",b);g.Am(c,"TYPE","terminate");C7(a,c);b=new m7(a,a.o,b,void 0);b.Jj=2;b.hh=P6(c.clone());(new window.Image).src=b.hh;b.wk=(0,g.F)();o7(b)}PBa(a)},RBa=function(a){a.aJ(1,0);
a.bo=y7(a,null,a.Yr);D7(a)},OBa=function(a){a.Yg&&(a.Yg.abort(),a.Yg=null);
a.tc&&(a.tc.cancel(),a.tc=null);a.pg&&(g.w.clearTimeout(a.pg),a.pg=null);E7(a);a.Vd&&(a.Vd.cancel(),a.Vd=null);a.ah&&(g.w.clearTimeout(a.ah),a.ah=null)},SBa=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.l.push(new KBa(a.JP++,b));2!=a.g&&3!=a.g||D7(a)},D7=function(a){a.Vd||a.ah||(a.ah=v7((0,g.z)(a.PC,a),0),a.vj=0)},UBa=function(a,b){if(1==a.g){if(!b){a.gm=Math.floor(1E5*Math.random());
var c=a.gm++,d=new m7(a,"",c,void 0);d.ki=null;var e=F7(a),f=a.bo.clone();g.Am(f,"RID",c);g.Am(f,"CVER","1");C7(a,f);zBa(d,f,e);a.Vd=d;a.g=2}}else 3==a.g&&(b?TBa(a,b):0==a.l.length||a.Vd||TBa(a))},TBa=function(a,b){if(b)if(6<a.Wh){a.l=a.A.concat(a.l);
a.A.length=0;var c=a.gm-1;var d=F7(a)}else c=b.D,d=b.Ni;else c=a.gm++,d=F7(a);var e=a.bo.clone();g.Am(e,"SID",a.o);g.Am(e,"RID",c);g.Am(e,"AID",a.Xj);C7(a,e);c=new m7(a,a.o,c,a.vj+1);c.ki=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Vd=c;zBa(c,e,d)},C7=function(a,b){if(a.nd){var c=a.nd.Hy();
c&&g.Jb(c,function(a,c){g.Am(b,c,a)})}},F7=function(a){var b=Math.min(a.l.length,1E3),c=["count="+b];
if(6<a.Wh&&0<b){var d=a.l[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.l[e].g,k=a.l[e].map;f=6>=a.Wh?e:f-d;try{g.Jb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.A=a.A.concat(a.l.splice(0,b));
return c.join("&")},VBa=function(a){a.tc||a.pg||(a.D=1,a.pg=v7((0,g.z)(a.OC,a),0),a.ij=0)},G7=function(a){if(a.tc||a.pg||3<=a.ij)return!1;
a.D++;a.pg=v7((0,g.z)(a.OC,a),WBa(a,a.ij));a.ij++;return!0},z7=function(a,b,c){a.pq=c;
a.Pf=b.Ag;a.C||RBa(a)},E7=function(a){null!=a.Yh&&(g.w.clearTimeout(a.Yh),a.Yh=null)},WBa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},H7=function(a,b){if(2==b||9==b){var c=null;
a.nd&&(c=null);var d=(0,g.z)(a.GV,a);c||(c=new g.rm("//www.google.com/images/cleardot.gif"),P6(c));GBa(c.toString(),1E4,d)}else q7(2);XBa(a,b)},XBa=function(a,b){a.g=0;
a.nd&&a.nd.Bx(b);PBa(a);OBa(a)},PBa=function(a){a.g=0;
a.Pf=-1;if(a.nd)if(0==a.A.length&&0==a.l.length)a.nd.jr();else{g.Xa(a.A);var b=g.Xa(a.l);a.A.length=0;a.l.length=0;a.nd.jr(b)}},y7=function(a,b,c){var d=g.Bm(c);
if(""!=d.l)b&&g.tm(d,b+"."+d.l),g.um(d,d.B);else{var e=window.location;d=XAa(e.protocol,b?b+"."+e.hostname:e.hostname,e.port,c)}a.jl&&g.Jb(a.jl,function(a,b){g.Am(d,b,a)});
g.Am(d,"VER",a.Wh);C7(a,d);return d},v7=function(a,b){if(!g.Ba(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},q7=function(a){I7.dispatchEvent(new LBa(I7,a))},YBa=function(){},ZBa=function(a,b){this.action=a;
this.params=b||{}},J7=function(a,b){g.M.call(this);
this.g=new g.Vt(this.LT,0,this);g.N(this,this.g);this.od=5E3;this.l=0;if(g.Ba(a))b&&(a=(0,g.z)(a,b));else if(a&&g.Ba(a.handleEvent))a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.o=a},K7=function(a,b,c){this.J=a;
this.C=b;this.o=new g.TC;this.l=new J7(this.mW,this);this.g=this.Ya=null;this.I=!1;this.B=null;this.H="";this.F=this.A=0;this.D=[];this.K=c||!1},$Ba=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.pq,sessionId:a.g.o,arrayId:a.g.Xj}},aCa=function(a,b){a.F=b||0;
a.l.stop();a.g&&(3==a.g.g&&UBa(a.g),QBa(a.g));a.F=0},L7=function(a){return!!a.g&&3==a.g.g},bCa=function(a,b){(a.C.loungeIdToken=b)||a.l.stop()},M7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.l=!0;a=a||window.document.location.href;var b=g.Hg(a)||"";b&&(this.port=":"+b);this.domain=g.Gg(a)||"";a=g.Hb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ab(a,"10.0")&&(this.l=!1))},N7=function(a,b){var c=a.g;
if(g.t(void 0)?0:a.l)c="https://"+a.domain+a.port+a.g;return g.Qg(c+b,{})},O7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Fa(a.A,d,!0),onError:g.Fa(a.o,e),ud:g.Fa(a.B,e)};c&&(a.Lb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.jE(b,a)},fCa=function(){var a=cCa;
dCa();P7.push(a);eCa(P7)},Q7=function(a,b){dCa();
var c=P7,d=gCa(a,String(b));g.Qa(c)?hCa(d):(eCa(c),(0,g.B)(c,function(a){a(d)}))},dCa=function(){P7||(P7=g.x("yt.mdx.remote.debug.handlers_")||[],g.wa("yt.mdx.remote.debug.handlers_",P7,void 0))},hCa=function(a){var b=(R7+1)%50;
R7=b;S7[b]=a;T7||(T7=49==b)},eCa=function(a){var b=S7;
if(b[0]){var c=R7,d=T7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.B)(a,function(a){a(e)})}while(d!=c);
S7=Array(50);R7=-1;T7=!1}},gCa=function(a,b){var c=((0,g.F)()-iCa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},U7=function(a){g.EF.call(this);
this.D=a;this.g=[]},jCa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},kCa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Kd)(a.g,function(a){return!!X6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=jCa(a,b[d])||c;return c},lCa=function(a,b){var c=a.g.length;
a.g=(0,g.Kd)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},V7=function(a,b,c,d){g.EF.call(this);
this.C=a;this.B=b;this.o=c;this.A=d;this.l=0;this.g=null;this.Ba=window.NaN},X7=function(a){U7.call(this,"LocalScreenService");
this.o=a;this.l=window.NaN;W7(this);this.info("Initializing with "+V6(this.g))},mCa=function(a){if(a.g.length){var b=(0,g.G)(a.g,function(a){return a.id}),c=N7(a.o,"/pairing/get_lounge_token_batch");
O7(a.o,c,{screen_ids:b.join(",")},(0,g.z)(a.FJ,a),(0,g.z)(a.EJ,a))}},W7=function(a){var b=eBa(kBa());
b=(0,g.Kd)(b,function(a){return!a.uuid});
return kCa(a,b)},Y7=function(a,b){mBa((0,g.G)(a.g,cBa));
b&&lBa()},$7=function(a,b){g.EF.call(this);
this.C=b;var c=g.LG("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Pa(c,l)}this.g=d;this.B=a;this.o=this.A=window.NaN;this.l=null;Z7("Initialized with "+g.yg(this.g))},nCa=function(a,b,c){var d=N7(a.B,"/pairing/get_screen_availability");
O7(a.B,d,{lounge_token:b.token},(0,g.z)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},a8=function(a,b){a:if(g.Nb(b)!=g.Nb(a.g))var c=!1;
else{c=g.Qb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(Z7("Updated online screens: "+g.yg(a.g)),a.g=b,a.T("screenChange"));oCa(a)},b8=function(a){(0,window.isNaN)(a.o)||g.VD(a.o);
a.o=g.TD((0,g.z)(a.av,a),0<a.A&&a.A<(0,g.F)()?2E4:1E4)},Z7=function(a){Q7("OnlineScreenService",a)},pCa=function(a){var b={};
(0,g.B)(a.C(),function(a){a.token?b[a.token]=a.id:this.dc("Requesting availability of screen w/o lounge token.")});
return b},oCa=function(a){a=g.Qb(g.Kb(a.g,function(a){return a}));
g.gb(a);a.length?g.KG("yt-remote-online-screen-ids",a.join(","),60):g.MG("yt-remote-online-screen-ids")},c8=function(a){U7.call(this,"ScreenService");
this.C=a;this.l=this.o=null;this.A=[];this.B={};qCa(this)},sCa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.ie();if(k=(c?Y6(k,c):null)||Y6(k,b)){k.uuid=b;var l=d8(a,k);nCa(a.l,l,function(a){e(a?l:null)})}else c?rCa(a,c,(0,g.z)(function(a){var f=d8(this,new S6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));nCa(this.l,f,function(a){e(a?f:null)})},a),f):e(null)},tCa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},rCa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Lb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.jE(N7(a.C,"/pairing/get_lounge_token_batch"),e)},uCa=function(a){a.g=a.o.ie();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+V6(a.g))},qCa=function(a){e8(a);
a.o=new X7(a.C);a.o.subscribe("screenChange",(0,g.z)(a.UJ,a));uCa(a);a.A=eBa(g.LG("yt-remote-automatic-screen-cache")||[]);e8(a);a.info("Initializing automatic screens: "+V6(a.A));a.l=new $7(a.C,(0,g.z)(a.ie,a,!0));a.l.subscribe("screenChange",(0,g.z)(function(){this.T("onlineScreenChange")},a))},d8=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=Y6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.KG("yt-remote-automatic-screen-cache",(0,g.G)(a.A,cBa)));e8(a);a.B[b.uuid]=b.id;g.KG("yt-remote-device-id-map",a.B,31536E3);return b},e8=function(a){a.B=g.LG("yt-remote-device-id-map")||{}},f8=function(a,b,c){g.EF.call(this);
this.K=c;this.H=a;this.l=b;this.o=null},g8=function(a,b){Q7(a.K,b)},h8=function(a,b){f8.call(this,a,b,"CastSession");
this.g=null;this.A=0;this.C=(0,g.z)(this.sW,this);this.B=(0,g.z)(this.zU,this);this.A=g.TD((0,g.z)(function(){vCa(this,null)},this),12E4)},wCa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.yg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.y,(0,g.z)(function(){g8(this,"Failed to send message: getMdxSessionStatus.")},a)):g8(a,"Sending yt message without session: "+g.yg(b))},vCa=function(a,b){g.VD(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.z)(a.tp,a),d=(0,g.z)(a.pe,a);a.Ry(b,c,d,5)}}else a.pe(Error("Waiting for session status timed out."))},i8=function(a,b,c){f8.call(this,a,b,"DialSession");
this.A=this.F=null;this.I="";this.M=c;this.B=null;this.D=g.y;this.C=window.NaN;this.J=(0,g.z)(this.vW,this);this.g=g.y},xCa=function(a){a.g=a.H.bF(a.I,a.l.label,a.l.friendlyName,(0,g.z)(function(a){this.g=g.y;
this.tp(a)},a),(0,g.z)(function(a){this.g=g.y;
this.pe(a)},a))},yCa=function(a){var b={};
b.pairingCode=a.I;b.theme=a.M;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}oBa()&&(b.env_useStageMdx=1);return g.Og(b)},j8=function(a,b){f8.call(this,a,b,"ManualSession");
this.g=g.TD((0,g.z)(this.Zj,this,null),150)},k8=function(a,b,c,d){g.EF.call(this);
this.l=a;this.D=b||"233637DE";this.C=c||"cl";this.F=d||!1;this.g=null;this.B=!1;this.o=[];this.A=(0,g.z)(this.XS,this)},zCa=function(a,b){return b?g.La(a.o,function(a){return T6(b,a.label)},a):null},l8=function(a){Q7("Controller",a)},cCa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},m8=function(a){return a.B||!!a.o.length||!!a.g},n8=function(a,b,c){b!=a.g&&(g.$e(a.g),(a.g=b)?(c?a.T("yt-remote-cast2-receiver-resumed",b.l):a.T("yt-remote-cast2-receiver-selected",
b.l),b.subscribe("sessionScreen",(0,g.z)(a.MC,a,b)),b.o?a.T("yt-remote-cast2-session-change",b.o):c&&a.g.Zj(null)):a.T("yt-remote-cast2-session-change",null))},ACa=function(a){var b=a.l.aF(),c=a.g&&a.g.l;
a=(0,g.G)(b,function(a){c&&T6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=zCa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},GCa=function(a,b,c,d,e,f,k){BCa()?CCa(b,e,f,k)&&(p8(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?DCa(a,c):(window.__onGCastApiAvailable=function(b,d){b?DCa(a,c):(q8("Failed to load cast API: "+d),r8(!1),p8(!1),g.MG("yt-remote-cast-available"),g.MG("yt-remote-cast-receiver"),ECa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):rBa():i7("CriOS")?wBa():i7("Android")&&i7("Chrome/")&&window.navigator.presentation?xBa():window.chrome&&window.navigator.presentation&&!i7("Edge")?(j7(),f7(FCa.map(uBa))):g7())):o8("Cannot initialize because not running Chrome")},ECa=function(){o8("dispose");
var a=s8();a&&a.dispose();g.wa("yt.mdx.remote.cloudview.instance_",null,void 0);HCa(!1);g.RF(t8);t8.length=0},u8=function(){return!!g.LG("yt-remote-cast-installed")},ICa=function(){var a=g.LG("yt-remote-cast-receiver");
return a?a.friendlyName:null},JCa=function(){o8("clearCurrentReceiver");
g.MG("yt-remote-cast-receiver")},KCa=function(){return u8()?s8()?s8().getCastSession():(q8("getCastSelector: Cast is not initialized."),null):(q8("getCastSelector: Cast API is not installed!"),null)},w8=function(){u8()?s8()?v8()?(o8("Requesting cast selector."),s8().requestSession()):(o8("Wait for cast API to be ready to request the session."),t8.push(g.QF("yt-remote-cast2-api-ready",w8))):q8("requestCastSelector: Cast is not initialized."):q8("requestCastSelector: Cast API is not installed!")},x8=
function(a,b){v8()?s8().setConnectedScreenStatus(a,b):q8("setConnectedScreenStatus called before ready.")},BCa=function(){var a=0<=g.Hb.search(/ (CrMo|Chrome|CriOS)\//);
return g.wI||a},LCa=function(a,b){s8().init(a,b)},CCa=function(a,b,c,d){var e=!1;
s8()||(a=new k8(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.KG("yt-remote-cast-available",a);g.UF("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){o8("onReceiverSelected: "+a.friendlyName);
g.KG("yt-remote-cast-receiver",a);g.UF("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){o8("onReceiverResumed: "+a.friendlyName);
g.KG("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){o8("onSessionChange: "+U6(a));
a||g.MG("yt-remote-cast-receiver");g.UF("yt-remote-cast2-session-change",a)}),g.wa("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
o8("cloudview.createSingleton_: "+e);return e},s8=function(){return g.x("yt.mdx.remote.cloudview.instance_")},DCa=function(a,b){r8(!0);
p8(!1);LCa(a,function(a){a?(HCa(!0),g.TF("yt-remote-cast2-api-ready")):(q8("Failed to initialize cast API."),r8(!1),g.MG("yt-remote-cast-available"),g.MG("yt-remote-cast-receiver"),ECa());b(a)})},o8=function(a){Q7("cloudview",a)},q8=function(a){Q7("cloudview",a)},r8=function(a){o8("setCastInstalled_ "+a);
g.KG("yt-remote-cast-installed",a)},v8=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},HCa=function(a){o8("setApiReady_ "+a);
g.wa("yt.mdx.remote.cloudview.apiReady_",a,void 0)},p8=function(a){g.wa("yt.mdx.remote.cloudview.initializing_",a,void 0)},y8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.D=this.F=0;this.l=null;this.hasNext=this.Sf=!1;this.I=this.H=this.o=this.B=0;this.A=window.NaN;this.C=!1;this.reset(a)},z8=function(a){a.audioTrackId=null;
a.l=null;a.g=-1;a.Sf=!1;a.hasNext=!1;a.F=0;a.D=(0,g.F)();a.B=0;a.o=0;a.H=0;a.I=0;a.A=window.NaN;a.C=!1},A8=function(a){return a.kb()?((0,g.F)()-a.D)/1E3:0},B8=function(a,b){a.F=b;
a.D=(0,g.F)()},C8=function(a){switch(a.g){case 1:case 1081:return((0,g.F)()-a.D)/1E3+a.F;
case -1E3:return 0}return a.F},D8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&z8(a)},E8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.bc(a.l);b.hasPrevious=a.Sf;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.D;b.seekableStart=a.B;b.seekableEnd=a.o;b.duration=a.H;b.loadedTime=a.I;b.liveIngestionTime=a.A;return b},G8=function(a,b){g.EF.call(this);
this.g=0;this.A=a;this.C=[];this.B=new g.jC;this.o=this.l=null;this.H=(0,g.z)(this.tQ,this);this.D=(0,g.z)(this.jm,this);this.F=(0,g.z)(this.sQ,this);this.I=(0,g.z)(this.FQ,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Vv,this),MCa(this))):c=3;0!=c&&(b?this.Vv(c):g.TD((0,g.z)(function(){this.Vv(c)},this),0));
var d=KCa();d&&F8(this,d);this.subscribe("yt-remote-cast2-session-change",this.I)},H8=function(a){return new y8(a.A.getPlayerContextData())},MCa=function(a){(0,g.B)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.C.push(this.A.subscribe(a,g.Fa(this.RS,a),this))},a)},NCa=function(a){(0,g.B)(a.C,function(a){this.A.unsubscribeByKey(a)},a);
a.C.length=0},I8=function(a,b){50>a.B.Cc()&&g.lC(a.B,b)},K8=function(a,b,c){var d=H8(a);
B8(d,c);-1E3!=d.g&&(d.g=b);J8(a,d)},L8=function(a,b,c){a.A.sendMessage(b,c)},J8=function(a,b){NCa(a);
a.A.setPlayerContextData(E8(b));MCa(a)},F8=function(a,b){a.o&&(a.o.removeUpdateListener(a.H),a.o.removeMediaListener(a.D),a.jm(null));
a.o=b;a.o&&(Q7("CP","Setting cast session: "+a.o.sessionId),a.o.addUpdateListener(a.H),a.o.addMediaListener(a.D),a.o.media.length&&a.jm(a.o.media[0]))},OCa=function(a){var b=a.l.media,c=a.l.customData;
if(b&&c){var d=H8(a);b.contentId!=d.videoId&&Q7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;B8(d,a.l.getEstimatedTime());J8(a,d)}else Q7("CP","No cast media video. Ignoring state update.")},M8=function(a,b,c){return(0,g.z)(function(a){this.dc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.dc("Retrying "+b+" using MDx browser channel."),L8(this,b,c))},a)},N8=function(a,b,c){g.EF.call(this);
this.B=window.NaN;this.M=!1;this.I=this.H=this.J=this.K=window.NaN;this.R=[];this.A=this.D=this.o=this.Za=this.g=null;this.ra=a;this.R.push(g.nF(window,"beforeunload",(0,g.z)(this.wJ,this)));this.l=[];this.Za=new y8;this.Y=b.id;this.g=PCa(this,c);this.g.subscribe("handlerOpened",this.xQ,this);this.g.subscribe("handlerClosed",this.uQ,this);this.g.subscribe("handlerError",this.vQ,this);this.g.subscribe("handlerMessage",this.wQ,this);bCa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.Za.videoId;g.NG()&&g.KG("yt-remote-session-video-id",a)},this)},O8=function(a){Q7("conn",a)},PCa=function(a,b){return new K7(N7(a.ra,"/bc"),b)},P8=function(a,b){a.T("proxyStateChange",b)},QCa=function(a){a.B=g.TD((0,g.z)(function(){O8("Connecting timeout");
this.C(1)},a),2E4)},Q8=function(a){g.VD(a.B);
a.B=window.NaN},R8=function(a){g.VD(a.K);
a.K=window.NaN},RCa=function(a){S8(a);
a.J=g.TD((0,g.z)(function(){T8(this,"getNowPlaying")},a),2E4)},S8=function(a){g.VD(a.J);
a.J=window.NaN},TCa=function(a,b){b&&(Q8(a),R8(a));
b==(L7(a.g)&&(0,window.isNaN)(a.B))?b&&(P8(a,1),T8(a,"getSubtitlesTrack")):b?(a.X()&&a.Za.reset(),P8(a,1),T8(a,"getNowPlaying"),SCa(a)):a.C(1)},UCa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Za.videoId&&(g.Wb(b.params)?a.Za.l=null:a.Za.l=b.params,a.T("remotePlayerChange"))},VCa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.Za.listId=b.params.listId||a.Za.listId;D8(a.Za,c,d);a.T("remoteQueueChange")},XCa=function(a,b){b.params=b.params||{};
VCa(a,b);WCa(a,b);a.T("autoplayDismissed")},WCa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
B8(a.Za,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.Za.g&&(c=-1E3);a.Za.g=c;c=Number(b.params.loadedTime);a.Za.I=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.Za.H=(0,window.isNaN)(c)?0:c;c=a.Za;var d=Number(b.params.liveIngestionTime);c.A=d;c.C=(0,window.isNaN)(d)?!1:!0;c=a.Za;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=(0,window.isNaN)(d)?0:d;c.o=(0,window.isNaN)(e)?0:e;1==a.Za.g?RCa(a):S8(a);
a.T("remotePlayerChange")},YCa=function(a,b){if(-1E3!=a.Za.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Za.g=c;c=(0,window.parseInt)(b.params.currentTime,10);B8(a.Za,(0,window.isNaN)(c)?0:c);a.T("remotePlayerChange")}},ZCa=function(a,b){var c="true"==b.params.muted;
a.Za.volume=(0,window.parseInt)(b.params.volume,10);a.Za.muted=c;a.T("remotePlayerChange")},$Ca=function(a,b){a.D=b.params.videoId;
a.T("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},aDa=function(a,b){var c="true"==b.params.hasNext;
a.Za.Sf="true"==b.params.hasPrevious;a.Za.hasNext=c;a.T("previousNextChange")},SCa=function(a){g.VD(a.I);
a.I=g.TD((0,g.z)(a.C,a,1),864E5)},T8=function(a,b,c){c?O8("Sending: action="+b+", params="+g.yg(c)):O8("Sending: action="+b);
a.g.sendMessage(b,c)},U8=function(a){U7.call(this,"ScreenServiceProxy");
this.dd=a;this.l=[];this.l.push(this.dd.$_s("screenChange",(0,g.z)(this.qW,this)));this.l.push(this.dd.$_s("onlineScreenChange",(0,g.z)(this.tS,this)))},fDa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.ND("MDX_CONFIG")||b;gBa();b7();V8||(V8=new M7(b?b.loungeApiHost:void 0),oBa()&&(V8.g="/api/loungedev"));W8||(W8=g.x("yt.mdx.remote.deferredProxies_")||[],g.wa("yt.mdx.remote.deferredProxies_",W8,void 0));bDa();var c=X8();if(!c){var d=new c8(V8);g.wa("yt.mdx.remote.screenService_",d,void 0);c=X8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);GCa(a,d,function(a){a?Y8()&&x8(Y8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.UF("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.wa("yt.mdx.remote.initialized_",!0,void 0),Z8("Initializing: "+g.yg(b)),$8.push(g.QF("yt-remote-cast2-availability-change",function(){g.UF("yt-remote-receiver-availability-change")})),$8.push(g.QF("yt-remote-cast2-receiver-selected",function(){a9(null);
g.UF("yt-remote-auto-connect","cast-selector-receiver")})),$8.push(g.QF("yt-remote-cast2-receiver-resumed",function(){g.UF("yt-remote-receiver-resumed","cast-selector-receiver")})),$8.push(g.QF("yt-remote-cast2-session-change",cDa)),$8.push(g.QF("yt-remote-connection-change",function(a){a?x8(Y8(),"YouTube TV"):b9()||(x8(null,null),JCa())})),a=c9(),b.isAuto&&(a.id+="#dial"),g.KF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),Z8(" -- with channel params: "+
g.yg(a)),dDa(a),c.start(),Y8()||eDa())},hDa=function(){var a=gDa();
u8()&&g.LG("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},gDa=function(){var a=X8().dd.$_gos();
var b=d9();b&&e9()&&(X6(a,b)||a.push(b));return fBa(a)},f9=function(){var a=iDa();
!a&&u8()&&ICa()&&(a={key:"cast-selector-receiver",name:ICa()});return a},iDa=function(){var a=gDa(),b=d9();
b||(b=b9());return g.La(a,function(a){return b&&T6(b,a.key)?!0:!1})},d9=function(){var a=Y8();
if(!a)return null;var b=X8().ie();return Y6(b,a)},cDa=function(a){Z8("remote.onCastSessionChange_: "+U6(a));
if(a){var b=d9();b&&b.id==a.id?x8(b.id,"YouTube TV"):(b&&g9(),h9(a,1))}else e9()&&g9()},g9=function(){v8()?s8().stopSession():q8("stopSession called before API ready.");
var a=e9();a&&(a.disconnect(1),i9(null))},j9=function(){var a=e9();
return!!a&&3!=a.getProxyState()},Z8=function(a){Q7("remote",a)},X8=function(){if(!k9){var a=g.x("yt.mdx.remote.screenService_");
k9=a?new U8(a):null}return k9},Y8=function(){return g.x("yt.mdx.remote.currentScreenId_")},jDa=function(a){g.wa("yt.mdx.remote.currentScreenId_",a,void 0)},kDa=function(){return g.x("yt.mdx.remote.connectData_")},a9=function(a){g.wa("yt.mdx.remote.connectData_",a,void 0)},e9=function(){return g.x("yt.mdx.remote.connection_")},i9=function(a){var b=e9();
a9(null);a||jDa("");g.wa("yt.mdx.remote.connection_",a,void 0);W8&&((0,g.B)(W8,function(b){b(a)}),W8.length=0);
b&&!a?g.UF("yt-remote-connection-change",!1):!b&&a&&g.UF("yt-remote-connection-change",!0)},b9=function(){var a=g.NG();
if(!a)return null;var b=X8().ie();return Y6(b,a)},h9=function(a,b){d9()&&d9();
jDa(a.id);var c=new N8(V8,a,c9());c.connect(b,kDa());c.subscribe("beforeDisconnect",function(a){g.UF("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){e9()&&i9(null)});
i9(c)},eDa=function(){var a=b9();
a?(Z8("Resume connection to: "+U6(a)),h9(a,0)):(c7(),JCa(),Z8("Skipping connecting because no session screen found."))},bDa=function(){var a=c9();
if(g.Wb(a)){a=a7();var b=g.LG("yt-remote-session-name")||"",c=g.LG("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.wa("yt.mdx.remote.channelParams_",a,void 0)}},c9=function(){return g.x("yt.mdx.remote.channelParams_")||{}},dDa=function(a){a?(g.KG("yt-remote-session-app",a.app),g.KG("yt-remote-session-name",a.name)):(g.MG("yt-remote-session-app"),g.MG("yt-remote-session-name"));
g.wa("yt.mdx.remote.channelParams_",a,void 0)},l9=function(a,b,c){g.M.call(this);
this.F=a;this.l=b;this.o=new g.BF(this);g.N(this,this.o);this.o.O(b,"onCaptionsTrackListChanged",this.NR);this.o.O(b,"captionschanged",this.rQ);this.o.O(b,"captionssettingschanged",this.oE);this.o.O(b,"videoplayerreset",this.up);this.o.O(b,"mdxautoplaycancel",this.CI);this.R=this.o.O(b,"onVolumeChange",this.wC);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.JC,this);c.subscribe("remotePlayerChange",this.pm,this);c.subscribe("remoteQueueChange",this.up,this);c.subscribe("autoplayUpNext",this.hC,
this);c.subscribe("previousNextChange",this.GC,this);c.subscribe("nowAutoplaying",this.yC,this);c.subscribe("autoplayDismissed",this.gC,this);this.suggestion=null;this.H=new g.vP(64);this.A=new g.Vt(this.kE,500,this);g.N(this,this.A);this.B=new g.Vt(this.lE,1E3,this);g.N(this,this.B);this.J=new k7(this.UV,0,this);g.N(this,this.J);this.C={};this.K=new g.Vt(this.LE,1E3,this);g.N(this,this.K);this.I=new g.Rk(this.qO,1E3,this);g.N(this,this.I);this.M=g.y;this.oE();this.up();this.pm()},m9=function(a,b){var c=
a.F,d=a.l.getVideoData().lengthSeconds;
c.H=b||0;c.g.T("progresssync",b,d)},lDa=function(a){m9(a,0);
a.A.stop();n9(a,new g.vP(64))},p9=function(a,b){if(o9(a)&&!a.D){var c=null;
b&&(c={style:a.l.Fi()},g.dc(c,b));a.g.YD(a.l.getVideoData(1).videoId,c);a.C=H8(a.g).l}},q9=function(a,b){var c=a.l.cg();
if(c){var d=c.ge();var e=c.listId.toString()}var f=a.l.getVideoData(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;var m=f.Sj;f=WAa(f);var n=H8(c);l=l||0;var q={videoId:k,currentIndex:l};D8(n,k,l);g.t(b)&&(B8(n,b),q.currentTime=b);g.t(e)&&(q.listId=e);null!=d&&(q.playerParams=d);null!=m&&(q.clickTrackingParams=m);null!=f&&(q.locationInfo=g.yg(f));L8(c,"setPlaylist",q);e||J8(c,n);n9(a,new g.vP(1))},mDa=function(a,b){if(b){var c=a.l.xc("captions","tracklist",{Nz:1});
c&&c.length?(a.l.Jd("captions","track",b),a.D=!1):(a.l.gk("captions"),a.D=!0)}else a.l.Jd("captions","track",{})},o9=function(a){return H8(a.g).videoId==a.l.getVideoData(1).videoId},n9=function(a,b){a.B.stop();
var c=a.H;if(!g.AP(c,b)){var d=g.X(b,2);d!=g.X(a.H,2)&&g.bV(a.l,d);a.H=b;nDa(a.F,c,b)}},r9=function(a){g.W.call(this,{G:"div",
L:"ytp-remote",N:[{G:"div",L:"ytp-remote-display-status",N:[{G:"div",L:"ytp-remote-display-status-icon",N:[g.Ooa()]},{G:"div",L:"ytp-remote-display-status-text",aa:"{{statustext}}"}]}]});this.o=new g.QV(this,250);g.N(this,this.o);this.A=a;this.O(a,"presentingplayerstatechange",this.B);oDa(this,g.ZU(a))},oDa=function(a,b){if(3==a.A.Pa()){var c={RECEIVER_NAME:a.A.xc("remote","currentReceiver").name};
c=g.X(b,128)?g.R0("Error on $RECEIVER_NAME",c):b.kb()||g.X(b,4)?g.R0("Playing on $RECEIVER_NAME",c):g.R0("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.o.show()}else a.o.hide()},s9=function(a,b){g.$Z.call(this,"Play on",0,a,b);
this.o=a;this.H={};this.O(a,"onMdxReceiversChange",this.J);this.O(a,"presentingplayerstatechange",this.J);this.J()},t9=function(a){g.wV.call(this,a);
this.o={key:W6(),name:"This computer"};this.B=null;this.C=[];this.I=this.l=null;this.F=[this.o];this.A=this.o;this.D=new g.vP(64);this.H=0;if(!g.PM(g.Y(this.g))){a=this.g;var b=g.BH(a);b&&(b=b.Qo())&&(b=new s9(a,b),g.N(this,b));b=new r9(a);g.N(this,b);g.qV(a,b.element,4)}},nDa=function(a,b,c){a.D=c;
a.g.T("presentingplayerstatechange",new g.FP(c,b))},u9=function(a,b){if(b.key!=a.A.key)if(b.key==a.o.key)g9();
else{a.A=b;var c=a.g.getPlaylistId();var d=a.g.getVideoData(1);var e=d.videoId;if(c||e){var f=a.g.cg();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Xb(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.Sj,index:Math.max(a.g.OA(),0),currentTime:0==f?void 0:f};(d=WAa(d))&&(c.locationInfo=d);d=c}else d=null;Z8("Connecting to: "+g.yg(b));"cast-selector-receiver"==b.key?(a9(d||null),v8()?s8().setLaunchParams(d||null):
q8("setLaunchParams called before ready.")):!d&&j9()&&Y8()==b.key?g.UF("yt-remote-connection-change",!0):(g9(),a9(d||null),d=X8().ie(),(d=Y6(d,b.key))&&h9(d,1))}},DBa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},u7={"'":"\\'"},pDa={},bBa={HX:"atp",f2:"ska",v1:"que",G0:"mus",b2:"sus",PZ:"dsp"};
R6.prototype.Kn=function(){var a=new R6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.o=this.o;a.l=this.l;a.g=this.g};
var d7,$6="",h7=e7("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",vBa=e7("loadCastFramework")||e7("loadCastApplicationFramework"),FCa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(k7,g.M);g.h=k7.prototype;g.h.rJ=function(a){this.A=arguments;this.g=!1;this.Ba?this.o=(0,g.F)()+this.od:this.Ba=g.sg(this.B,this.od)};
g.h.stop=function(){this.Ba&&(g.tg(this.Ba),this.Ba=null);this.o=null;this.g=!1;this.A=[]};
g.h.pause=function(){++this.l};
g.h.resume=function(){this.l&&(--this.l,!this.l&&this.g&&(this.g=!1,this.C.apply(null,this.A)))};
g.h.V=function(){this.stop();k7.ba.V.call(this)};
g.h.sJ=function(){this.o?(this.Ba=g.sg(this.B,this.o-(0,g.F)()),this.o=null):(this.Ba=null,this.l?this.g=!0:(this.g=!1,this.C.apply(null,this.A)))};l7.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
l7.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=m7.prototype;g.h.ki=null;g.h.Cf=!1;g.h.Mk=null;g.h.Ov=null;g.h.wk=null;g.h.Jj=null;g.h.hh=null;g.h.Gh=null;g.h.Ni=null;g.h.Pc=null;g.h.Km=0;g.h.Df=null;g.h.qq=null;g.h.ih=null;g.h.zl=-1;g.h.FD=!0;g.h.Uh=!1;g.h.es=0;g.h.Fp=null;var BBa={},p7={};g.h=m7.prototype;g.h.setTimeout=function(a){this.A=a};
g.h.OU=function(a){a=a.target;var b=this.Fp;b&&3==g.fx(a)?b.Hj():this.UE(a)};
g.h.UE=function(a){try{if(a==this.Pc)a:{var b=g.fx(this.Pc),c=this.Pc.l,d=this.Pc.getStatus();if(g.xd&&!g.qc(10)||g.zd&&!g.pc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.df&&!g.jx(this.Pc))break a;this.Uh||4!=b||7==c||(8==c||0>=d?this.g.wf(3):this.g.wf(2));w7(this);var e=this.Pc.getStatus();this.zl=e;var f=g.jx(this.Pc);(this.Cf=200==e)?(4==b&&s7(this),this.B?(CBa(this,b,f),g.df&&this.Cf&&3==b&&(this.W.U(this.l,"tick",this.KU),this.l.start())):r7(this,f),this.Cf&&!this.Uh&&(4==b?this.g.rp(this):
(this.Cf=!1,o7(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.ih=3,q7(13)):(this.ih=0,q7(14)),s7(this),t7(this))}}catch(k){this.Pc&&g.jx(this.Pc)}finally{}};
g.h.KU=function(){var a=g.fx(this.Pc),b=g.jx(this.Pc);this.Km<b.length&&(w7(this),CBa(this,a,b),this.Cf&&4!=a&&o7(this))};
g.h.VT=function(a){v7((0,g.z)(this.UT,this,a),0)};
g.h.UT=function(a){this.Uh||(w7(this),r7(this,a),o7(this))};
g.h.RC=function(a){v7((0,g.z)(this.TT,this,a),0)};
g.h.TT=function(a){this.Uh||(s7(this),this.Cf=a,this.g.rp(this),this.g.wf(4))};
g.h.cancel=function(){this.Uh=!0;s7(this)};
g.h.nU=function(){this.Mk=null;var a=(0,g.F)();0<=a-this.Ov?(2!=this.Jj&&this.g.wf(3),s7(this),this.ih=2,q7(18),t7(this)):FBa(this,this.Ov-a)};g.h=IBa.prototype;g.h.Zr=null;g.h.re=null;g.h.Gp=!1;g.h.az=null;g.h.Xn=null;g.h.jt=null;g.h.ds=null;g.h.Me=null;g.h.Ag=-1;g.h.yl=null;g.h.Tk=null;g.h.connect=function(a){this.ds=a;a=y7(this.g,null,this.ds);q7(3);this.az=(0,g.F)();var b=this.g.F;null!=b?(this.yl=b[0],(this.Tk=b[1])?(this.Me=1,JBa(this)):(this.Me=2,A7(this))):(Q6(a,"MODE","init"),this.re=new m7(this,void 0,void 0,void 0),this.re.ki=this.Zr,n7(this.re,a,!1,null,!0),this.Me=0)};
g.h.DI=function(a){if(a)this.Me=2,A7(this);else{q7(4);var b=this.g;b.Pf=b.Yg.Ag;H7(b,9)}a&&this.wf(2)};
g.h.xr=function(a){return this.g.xr(a)};
g.h.abort=function(){this.re&&(this.re.cancel(),this.re=null);this.Ag=-1};
g.h.Zy=function(){return!1};
g.h.KC=function(a,b){this.Ag=a.zl;if(0==this.Me)if(b){try{var c=this.l.parse(b)}catch(d){c=this.g;c.Pf=this.Ag;H7(c,2);return}this.yl=c[0];this.Tk=c[1]}else c=this.g,c.Pf=this.Ag,H7(c,2);else if(2==this.Me)if(this.Gp)q7(7),this.jt=(0,g.F)();else if("11111"==b){if(q7(6),this.Gp=!0,this.Xn=(0,g.F)(),c=this.Xn-this.az,!g.xd||g.qc(10)||500>c)this.Ag=200,this.re.cancel(),q7(12),z7(this.g,this,!0)}else q7(8),this.Xn=this.jt=(0,g.F)(),this.Gp=!1};
g.h.rp=function(){this.Ag=this.re.zl;if(this.re.Cf)0==this.Me?this.Tk?(this.Me=1,JBa(this)):(this.Me=2,A7(this)):2==this.Me&&((!g.xd||g.qc(10)?!this.Gp:200>this.jt-this.Xn)?(q7(11),z7(this.g,this,!1)):(q7(12),z7(this.g,this,!0)));else{0==this.Me?q7(9):2==this.Me&&q7(10);var a=this.g;a.Pf=this.Ag;H7(a,2)}};
g.h.Bm=function(){return this.g.Bm()};
g.h.isActive=function(){return this.g.isActive()};
g.h.wf=function(a){this.g.wf(a)};g.h=B7.prototype;g.h.jl=null;g.h.Vd=null;g.h.tc=null;g.h.Yr=null;g.h.bo=null;g.h.ox=null;g.h.qo=null;g.h.gm=0;g.h.JP=0;g.h.nd=null;g.h.ah=null;g.h.pg=null;g.h.Yh=null;g.h.Yg=null;g.h.pq=null;g.h.Xj=-1;g.h.cA=-1;g.h.Pf=-1;g.h.vj=0;g.h.ij=0;g.h.Wh=8;var I7=new g.Df;g.A(LBa,g.bf);g.A(MBa,g.bf);g.A(NBa,g.bf);g.h=B7.prototype;g.h.connect=function(a,b,c,d,e){q7(0);this.Yr=b;this.jl=c||{};d&&g.t(e)&&(this.jl.OSID=d,this.jl.OAID=e);this.C?(v7((0,g.z)(this.Mx,this,a),100),RBa(this)):this.Mx(a)};
g.h.Mx=function(a){this.Yg=new IBa(this);this.Yg.Zr=null;this.Yg.l=this.B;this.Yg.connect(a)};
g.h.Zy=function(){return 0==this.g};
g.h.PC=function(a){this.ah=null;UBa(this,a)};
g.h.OC=function(){this.pg=null;this.tc=new m7(this,this.o,"rpc",this.D);this.tc.ki=null;this.tc.es=0;var a=this.ox.clone();g.Am(a,"RID","rpc");g.Am(a,"SID",this.o);g.Am(a,"CI",this.pq?"0":"1");g.Am(a,"AID",this.Xj);C7(this,a);if(!g.xd||g.qc(10))g.Am(a,"TYPE","xmlhttp"),n7(this.tc,a,!0,this.qo,!1);else{g.Am(a,"TYPE","html");var b=this.tc,c=!!this.qo;b.Jj=3;b.hh=P6(a.clone());EBa(b,c)}};
g.h.KC=function(a,b){if(0!=this.g&&(this.tc==a||this.Vd==a))if(this.Pf=a.zl,this.Vd==a&&3==this.g)if(7<this.Wh){try{var c=this.B.parse(b)}catch(f){c=null}if(g.za(c)&&3==c.length)if(0==c[0])a:{if(!this.pg){if(this.tc)if(this.tc.wk+3E3<this.Vd.wk)E7(this),this.tc.cancel(),this.tc=null;else break a;G7(this);q7(19)}}else this.cA=c[1],0<this.cA-this.Xj&&37500>c[2]&&this.pq&&0==this.ij&&!this.Yh&&(this.Yh=v7((0,g.z)(this.mQ,this),6E3));else H7(this,11)}else b!=pDa.KY.g&&H7(this,11);else if(this.tc==a&&
E7(this),!g.C(b)){c=this.B.parse(b);g.za(c);for(var d=0;d<c.length;d++){var e=c[d];this.Xj=e[0];e=e[1];2==this.g?"c"==e[0]?(this.o=e[1],this.qo=e[2],e=e[3],null!=e?this.Wh=e:this.Wh=6,this.g=3,this.nd&&this.nd.Dx(),this.ox=y7(this,this.Bm()?this.qo:null,this.Yr),VBa(this)):"stop"==e[0]&&H7(this,7):3==this.g&&("stop"==e[0]?H7(this,7):"noop"!=e[0]&&this.nd&&this.nd.Cx(e),this.ij=0)}}};
g.h.mQ=function(){null!=this.Yh&&(this.Yh=null,this.tc.cancel(),this.tc=null,G7(this),q7(20))};
g.h.rp=function(a){if(this.tc==a){E7(this);this.tc=null;var b=2}else if(this.Vd==a)this.Vd=null,b=1;else return;this.Pf=a.zl;if(0!=this.g)if(a.Cf)1==b?(b=(0,g.F)()-a.wk,I7.dispatchEvent(new MBa(I7,a.Ni?a.Ni.length:0,b,this.vj)),D7(this),this.A.length=0):VBa(this);else{var c=a.ih,d;if(!(d=3==c||7==c||0==c&&0<this.Pf)){if(d=1==b)this.Vd||this.ah||1==this.g||2<=this.vj?d=!1:(this.ah=v7((0,g.z)(this.PC,this,a),WBa(this,this.vj)),this.vj++,d=!0);d=!(d||2==b&&G7(this))}if(d)switch(c){case 1:H7(this,5);
break;case 4:H7(this,10);break;case 3:H7(this,6);break;case 7:H7(this,12);break;default:H7(this,2)}}};
g.h.aJ=function(a){if(!g.Pa(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.GV=function(a){a?q7(2):(q7(1),XBa(this,8))};
g.h.xr=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.$w;a.F=!1;return a};
g.h.isActive=function(){return!!this.nd&&this.nd.isActive(this)};
g.h.wf=function(a){I7.dispatchEvent(new NBa(I7,a))};
g.h.Bm=function(){return!(!g.xd||g.qc(10))};
g.h=YBa.prototype;g.h.Dx=function(){};
g.h.Cx=function(){};
g.h.Bx=function(){};
g.h.jr=function(){};
g.h.Hy=function(){return{}};
g.h.isActive=function(){return!0};g.A(J7,g.M);g.h=J7.prototype;g.h.LT=function(){this.od=Math.min(3E5,2*this.od);this.o();this.l&&this.start()};
g.h.start=function(){var a=this.od+15E3*Math.random();g.Wt(this.g,a);this.l=(0,g.F)()+a};
g.h.stop=function(){this.g.stop();this.l=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.od=5E3};g.A(K7,YBa);g.h=K7.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.o.unsubscribe(a,b,c)};
g.h.Nd=function(a){return this.o.Nd(a)};
g.h.T=function(a,b){return this.o.T.apply(this.o,arguments)};
g.h.dispose=function(){this.I||(this.I=!0,g.$e(this.o),aCa(this),g.$e(this.l),this.l=null)};
g.h.ka=function(){return this.I};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.H="";this.l.stop();this.B=a||null;this.A=b||0;a=this.J+"/test";b=this.J+"/bind";var d=new B7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.K),e=this.g;e&&(e.nd=null);d.nd=this;this.g=d;e?this.g.connect(a,b,this.C,e.o,e.Xj):c?this.g.connect(a,b,this.C,c.sessionId,c.arrayId):this.g.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.dc(c,b);this.l.isActive()||2==(this.g?this.g.g:0)?this.D.push(c):L7(this)&&SBa(this.g,c)};
g.h.Dx=function(){this.l.reset();this.B=null;this.A=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)SBa(this.g,a[b])}this.T("handlerOpened")};
g.h.Bx=function(a){var b=2==a&&401==this.g.Pf;4==a||b||this.l.start();this.T("handlerError",a)};
g.h.jr=function(a){if(!this.l.isActive())this.T("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.Hy=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.F&&(a.ui=""+this.F);this.B&&g.dc(a,this.B);return a};
g.h.Cx=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),QBa(this.g)):this.T("handlerMessage",new ZBa(a[0],a[1]))};
g.h.mW=function(){this.l.isActive();var a=this.g,b=0;a.tc&&b++;a.Vd&&b++;0!=b||this.connect(this.B,this.A)};M7.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
M7.prototype.o=function(a,b){a(Error("Request error: "+b.status))};
M7.prototype.B=function(a){a(Error("request timed out"))};var iCa=(0,g.F)(),P7=null,S7=Array(50),R7=-1,T7=!1;g.A(U7,g.EF);U7.prototype.ie=function(){return this.g};
U7.prototype.contains=function(a){return!!X6(this.g,a)};
U7.prototype.get=function(a){return a?Y6(this.g,a):null};
U7.prototype.info=function(a){Q7(this.D,a)};g.A(V7,g.EF);var qDa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=V7.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.Ba)&&this.ZE()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.Ba)||(g.VD(this.Ba),this.Ba=window.NaN)};
g.h.V=function(){this.stop();V7.ba.V.call(this)};
g.h.ZE=function(){this.Ba=window.NaN;this.g=g.jE(N7(this.C,"/pairing/get_screen"),{method:"POST",Lb:{pairing_code:this.B},timeout:5E3,onSuccess:(0,g.z)(this.oW,this),onError:(0,g.z)(this.nW,this),ud:(0,g.z)(this.pW,this)})};
g.h.oW=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.o;c.name=this.A;this.T("pairingComplete",new S6(c))};
g.h.nW=function(a){this.g=null;a.status&&404==a.status?this.l>=qDa.length?this.T("pairingFailed",Error("DIAL polling timed out")):(a=qDa[this.l],this.Ba=g.TD((0,g.z)(this.ZE,this),a),this.l++):this.T("pairingFailed",Error("Server error "+a.status))};
g.h.pW=function(){this.g=null;this.T("pairingFailed",Error("Server not responding"))};g.A(X7,U7);g.h=X7.prototype;g.h.start=function(){W7(this)&&this.T("screenChange");!g.LG("yt-remote-lounge-token-expiration")&&mCa(this);g.VD(this.l);this.l=g.TD((0,g.z)(this.start,this),1E4)};
g.h.add=function(a,b){W7(this);jCa(this,a);Y7(this,!1);this.T("screenChange");b(a);a.token||mCa(this)};
g.h.remove=function(a,b){var c=W7(this);lCa(this,a)&&(Y7(this,!1),c=!0);b(a);c&&this.T("screenChange")};
g.h.kq=function(a,b,c,d){var e=W7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,Y7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.T("screenChange")};
g.h.V=function(){g.VD(this.l);X7.ba.V.call(this)};
g.h.FJ=function(a){W7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}Y7(this,!b);b&&Q7(this.D,"Missed "+b+" lounge tokens.")};
g.h.EJ=function(a){Q7(this.D,"Requesting lounge tokens failed: "+a)};g.A($7,g.EF);g.h=$7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.LG("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.F)()-144E5<a?0:a)?b8(this):(this.A=(0,g.F)()+3E5,g.KG("yt-remote-fast-check-period",this.A),this.av())};
g.h.isEmpty=function(){return g.Wb(this.g)};
g.h.update=function(){Z7("Updating availability on schedule.");var a=this.C(),b=g.Kb(this.g,function(b,d){return b&&!!Y6(a,d)},this);
a8(this,b)};
g.h.V=function(){g.VD(this.o);this.o=window.NaN;this.l&&(this.l.abort(),this.l=null);$7.ba.V.call(this)};
g.h.av=function(){g.VD(this.o);this.o=window.NaN;this.l&&this.l.abort();var a=pCa(this);if(g.Nb(a)){var b=N7(this.B,"/pairing/get_screen_availability");this.l=O7(this.B,b,{lounge_token:g.Qb(a).join(",")},(0,g.z)(this.sT,this,a),(0,g.z)(this.rT,this))}else a8(this,{}),b8(this)};
g.h.sT=function(a,b){this.l=null;var c=g.Qb(pCa(this));if(g.ib(c,g.Qb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;a8(this,d);b8(this)}else this.dc("Changing Screen set during request."),this.av()};
g.h.rT=function(a){this.dc("Screen availability failed: "+a);this.l=null;b8(this)};
g.h.dc=function(a){Q7("OnlineScreenService",a)};g.A(c8,U7);g.h=c8.prototype;g.h.start=function(){this.o.start();this.l.start();this.g.length&&(this.T("screenChange"),this.l.isEmpty()||this.T("onlineScreenChange"))};
g.h.add=function(a,b,c){this.o.add(a,b,c)};
g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.l.update()};
g.h.kq=function(a,b,c,d){this.o.contains(a)?this.o.kq(a,b,c,d):(a="Updating name of unknown screen: "+a.name,Q7(this.D,a),d(Error(a)))};
g.h.ie=function(a){return a?this.g:g.Wa(this.g,(0,g.Kd)(this.A,function(a){return!this.contains(a)},this))};
g.h.aF=function(){return(0,g.Kd)(this.ie(!0),function(a){return!!this.l.g[a.id]},this)};
g.h.bF=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new V7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(a){g.$e(f);d(d8(this,a))},this));
f.subscribe("pairingFailed",function(a){g.$e(f);e(a)});
f.start();return(0,g.z)(f.stop,f)};
g.h.rW=function(a,b,c,d){g.jE(N7(this.C,"/pairing/get_screen"),{method:"POST",Lb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.z)(function(a,d){var e=new S6(d.screen||{});if(!e.name||tCa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);tCa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(d8(this,e))},this),
onError:(0,g.z)(function(a){d(Error("pairing request failed: "+a.status))},this),
ud:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.h.V=function(){g.$e(this.o);g.$e(this.l);c8.ba.V.call(this)};
g.h.UJ=function(){uCa(this);this.T("screenChange");this.l.update()};
c8.prototype.dispose=c8.prototype.dispose;g.A(f8,g.EF);g.h=f8.prototype;g.h.tp=function(a){this.o=a;this.T("sessionScreen",this.o)};
g.h.pe=function(a){this.ka()||(a&&g8(this,""+a),this.o=null,this.T("sessionScreen",null))};
g.h.info=function(a){Q7(this.K,a)};
g.h.dF=function(){return null};
g.h.gv=function(a){var b=this.l;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){g8(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.V=function(){this.gv("");f8.ba.V.call(this)};g.A(h8,f8);g.h=h8.prototype;g.h.fv=function(a){if(this.g){if(this.g==a)return;g8(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.C);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.g=a;this.g.addUpdateListener(this.C);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);wCa(this)};
g.h.Zj=function(a){this.info("launchWithParams no-op for Cast: "+g.yg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.z)(function(){this.pe()},this),(0,g.z)(function(){this.pe(Error("Failed to stop receiver app."))},this)):this.pe(Error("Stopping cast device witout session."))};
g.h.gv=g.y;g.h.V=function(){this.info("disposeInternal");g.VD(this.A);this.A=0;this.g&&(this.g.removeUpdateListener(this.C),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.g=null;h8.ba.V.call(this)};
g.h.zU=function(a,b){if(!this.ka())if(b){var c=g.Uw(b);if(g.Ca(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.yg(c));switch(d){case "mdxSessionStatus":vCa(this,c.screenId);break;default:g8(this,"Unknown youtube message: "+d)}}else g8(this,"Unable to parse message.")}else g8(this,"No data in message.")};
g.h.Ry=function(a,b,c,d){sCa(this.H,this.l.label,a,this.l.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(g8(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.TD((0,g.z)(this.Ry,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.dF=function(){return this.g};
g.h.sW=function(a){this.ka()||a||(g8(this,"Cast session died."),this.pe())};g.A(i8,f8);g.h=i8.prototype;g.h.fv=function(a){this.A=a;this.A.addUpdateListener(this.J)};
g.h.Zj=function(a){this.B=a;this.D()};
g.h.stop=function(){this.g();this.g=g.y;g.VD(this.C);this.A?this.A.stop((0,g.z)(this.pe,this,null),(0,g.z)(this.pe,this,"Failed to stop DIAL device.")):this.pe()};
g.h.V=function(){this.g();this.g=g.y;g.VD(this.C);this.A&&this.A.removeUpdateListener(this.J);this.A=null;i8.ba.V.call(this)};
g.h.vW=function(a){this.ka()||a||(g8(this,"DIAL session died."),this.g(),this.g=g.y,this.pe())};
g.h.Ps=function(a){this.I=W6();if(this.B){var b=new window.chrome.cast.DialLaunchResponse(!0,yCa(this));a(b);xCa(this)}else this.D=(0,g.z)(function(){g.VD(this.C);this.D=g.y;this.C=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,yCa(this));a(b);xCa(this)},this),this.C=g.TD((0,g.z)(function(){this.D()},this),100)};
g.h.iL=function(a,b,c){sCa(this.H,this.F.receiver.label,a,this.l.friendlyName,(0,g.z)(function(a){a&&a.token?(this.tp(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.Ps(b,c)},this),(0,g.z)(function(a){g8(this,"Failed to get DIAL screen: "+a);
this.Ps(b,c)},this))};g.A(j8,f8);j8.prototype.stop=function(){this.pe()};
j8.prototype.fv=g.y;j8.prototype.Zj=function(){g.VD(this.g);this.g=window.NaN;var a=Y6(this.H.ie(),this.l.label);a?this.tp(a):this.pe(Error("No such screen"))};
j8.prototype.V=function(){g.VD(this.g);this.g=window.NaN;j8.ba.V.call(this)};g.A(k8,g.EF);g.h=k8.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.D);this.F||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.z)(this.LC,this),(0,g.z)(this.bT,this),d,e);c.customDialLaunchCallback=(0,g.z)(this.XQ,this);window.chrome.cast.initialize(c,
(0,g.z)(function(){this.ka()||(window.chrome.cast.addReceiverActionListener(this.A),fCa(),this.l.subscribe("onlineScreenChange",(0,g.z)(this.cF,this)),this.o=ACa(this),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.dc("Failed to set initial custom receivers: "+g.yg(a))},this)),this.T("yt-remote-cast2-availability-change",m8(this)),b(!0))},this),(0,g.z)(function(a){this.dc("Failed to initialize API: "+g.yg(a));
b(!1)},this))};
g.h.pV=function(a,b){l8("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.o;if(!a||c&&c.id!=a)l8("Unsetting old screen status: "+this.g.l.friendlyName),n8(this,null)}if(a&&b){if(!this.g){c=Y6(this.l.ie(),a);if(!c){l8("setConnectedScreenStatus: Unknown screen.");return}var d=zCa(this,c);d||(l8("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.o.push(d),
window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.dc("Failed to set initial custom receivers: "+g.yg(a))},this)));
l8("setConnectedScreenStatus: new active receiver: "+d.friendlyName);n8(this,new j8(this.l,d),!0)}this.g.gv(b)}else l8("setConnectedScreenStatus: no screen.")};
g.h.qV=function(a){this.ka()?this.dc("Setting connection data on disposed cast v2"):this.g?this.g.Zj(a):this.dc("Setting connection data without a session")};
g.h.uW=function(){this.ka()?this.dc("Stopping session on disposed cast v2"):this.g?(this.g.stop(),n8(this,null)):l8("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.z)(this.LC,this),(0,g.z)(this.xT,this))};
g.h.V=function(){this.l.unsubscribe("onlineScreenChange",(0,g.z)(this.cF,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.A);g.Ua(g.x("yt.mdx.remote.debug.handlers_")||[],cCa);g.$e(this.g);k8.ba.V.call(this)};
g.h.dc=function(a){Q7("Controller",a)};
g.h.MC=function(a,b){this.g==a&&(b||n8(this,null),this.T("yt-remote-cast2-session-change",b))};
g.h.XS=function(a,b){if(!this.ka())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),l8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.l.label!=a.label)l8("onReceiverAction_: Stopping active receiver: "+this.g.l.friendlyName),this.g.stop();else{l8("onReceiverAction_: Casting to active receiver.");this.g.o&&this.T("yt-remote-cast2-session-change",this.g.o);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:n8(this,
new j8(this.l,a));break;case window.chrome.cast.ReceiverType.DIAL:n8(this,new i8(this.l,a,this.C));break;case window.chrome.cast.ReceiverType.CAST:n8(this,new h8(this.l,a));break;default:this.dc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.l.label==a.label?this.g.stop():this.dc("Stopping receiver w/o session: "+a.friendlyName)}else this.dc("onReceiverAction_ called without receiver.")};
g.h.XQ=function(a){if(this.ka())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.dc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.l:null;if(!c||c.label!=b.label)return this.dc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.o)return l8("Reselecting dial screen."),
this.T("yt-remote-cast2-session-change",this.g.o),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.dc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);n8(this,new i8(this.l,b,this.C))}b=this.g;b.F=a;return b.F.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.z)(b.iL,b,(b.F.extraData||{}).screenId||null)):new window.Promise((0,g.z)(b.Ps,b))};
g.h.LC=function(a){if(!this.ka()){l8("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)l8("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),n8(this,new h8(this.l,b),!0);else{this.dc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.l,d=Y6(this.l.ie(),c.label);
d&&T6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(l8("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.$e(this.g),this.g=new h8(this.l,b),this.g.subscribe("sessionScreen",(0,g.z)(this.MC,this,this.g)),this.g.Zj(null));this.g.fv(a)}}};
g.h.tW=function(){return this.g?this.g.dF():null};
g.h.xT=function(a){this.ka()||(this.dc("Failed to estabilish a session: "+g.yg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&n8(this,null))};
g.h.bT=function(a){l8("Receiver availability updated: "+a);if(!this.ka()){var b=m8(this);this.B=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;m8(this)!=b&&this.T("yt-remote-cast2-availability-change",m8(this))}};
g.h.cF=function(){this.ka()||(this.o=ACa(this),l8("Updating custom receivers: "+g.yg(this.o)),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(){this.dc("Failed to set custom receivers.")},this)),this.T("yt-remote-cast2-availability-change",m8(this)))};
k8.prototype.setLaunchParams=k8.prototype.qV;k8.prototype.setConnectedScreenStatus=k8.prototype.pV;k8.prototype.stopSession=k8.prototype.uW;k8.prototype.getCastSession=k8.prototype.tW;k8.prototype.requestSession=k8.prototype.requestSession;k8.prototype.init=k8.prototype.init;k8.prototype.dispose=k8.prototype.dispose;var t8=[];g.h=y8.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";z8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.l=a.trackData,this.Sf=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.D=a.playerTimeAt,this.B=a.seekableStart,this.o=a.seekableEnd,this.H=a.duration,this.I=a.loadedTime,this.A=a.liveIngestionTime,this.C=!(0,window.isNaN)(this.A))};
g.h.kb=function(){return 1==this.g};
g.h.isAdPlaying=function(){return 1081==this.g};
g.h.getDuration=function(){return this.C?this.H+A8(this):this.H};
g.h.clone=function(){return new y8(E8(this))};g.A(G8,g.EF);g.h=G8.prototype;g.h.play=function(){1==this.g?(this.l?this.l.play(null,g.y,M8(this,"play")):L8(this,"play"),K8(this,1,C8(H8(this))),this.T("remotePlayerChange")):I8(this,this.play)};
g.h.pause=function(){1==this.g?(this.l?this.l.pause(null,g.y,M8(this,"pause")):L8(this,"pause"),K8(this,2,C8(H8(this))),this.T("remotePlayerChange")):I8(this,this.pause)};
g.h.YE=function(a){if(1==this.g){if(this.l){var b=H8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.kb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.l.seek(c,g.y,M8(this,"seekTo",{newTime:a}))}else L8(this,"seekTo",{newTime:a});K8(this,3,a);this.T("remotePlayerChange")}else I8(this,g.Fa(this.YE,a))};
g.h.stop=function(){if(1==this.g){this.l?this.l.stop(null,g.y,M8(this,"stopVideo")):L8(this,"stopVideo");var a=H8(this);a.index=-1;a.videoId="";z8(a);J8(this,a);this.T("remotePlayerChange")}else I8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=H8(this);if(this.o){if(c.volume!=a){var d=Math.round(a)/100;this.o.setReceiverVolumeLevel(d,(0,g.z)(function(){Q7("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.dc("failed to set receiver volume.")},this))}c.muted!=b&&this.o.setReceiverMuted(b,(0,g.z)(function(){Q7("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.dc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);L8(this,"setVolume",e)}c.muted=b;c.volume=a;J8(this,c)}else I8(this,g.Fa(this.setVolume,a,b))};
g.h.YD=function(a,b){if(1==this.g){var c=H8(this),d={videoId:a};b&&(c.l={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.yg(b.style),g.dc(d,c.l));L8(this,"setSubtitlesTrack",d);J8(this,c)}else I8(this,g.Fa(this.YD,a,b))};
g.h.Uv=function(a,b){if(1==this.g){L8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Fb.id});var c=H8(this);c.audioTrackId=b.Fb.id;J8(this,c)}else I8(this,g.Fa(this.Uv,a,b))};
g.h.XE=function(a,b){if(1==this.g){if(a&&b){var c=H8(this);D8(c,a,b);J8(this,c)}L8(this,"previous")}else I8(this,g.Fa(this.XE,a,b))};
g.h.WE=function(a,b){if(1==this.g){if(a&&b){var c=H8(this);D8(c,a,b);J8(this,c)}L8(this,"next")}else I8(this,g.Fa(this.WE,a,b))};
g.h.gy=function(){1==this.g?L8(this,"dismissAutoplay"):I8(this,this.gy)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.T("proxyStateChange",a,this.g)}G8.ba.dispose.call(this)};
g.h.V=function(){NCa(this);this.A=null;this.B.clear();F8(this,null);G8.ba.V.call(this)};
g.h.Vv=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.T("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)g.mC(this.B).apply(this);else 3==a&&this.dispose()}};
g.h.RS=function(a,b){this.T(a,b)};
g.h.tQ=function(a){if(!a)this.jm(null),F8(this,null);else if(this.o.receiver.volume){a=this.o.receiver.volume;var b=H8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)Q7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,J8(this,b)}};
g.h.jm=function(a){Q7("CP","Cast media: "+!!a);this.l&&this.l.removeUpdateListener(this.F);if(this.l=a)this.l.addUpdateListener(this.F),OCa(this),this.T("remotePlayerChange")};
g.h.sQ=function(a){a?(OCa(this),this.T("remotePlayerChange")):this.jm(null)};
g.h.FQ=function(){var a=KCa();a&&F8(this,a)};
g.h.dc=function(a){Q7("CP",a)};g.A(N8,g.EF);g.h=N8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.t(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.t(k)&&(l.currentIndex=k);c&&(this.Za.listId=c);this.Za.videoId=d;this.Za.index=k||0;this.Za.state=3;B8(this.Za,m);this.A="UNSUPPORTED";O8("Connecting with setPlaylist and params: "+g.yg(l));this.g.connect({method:"setPlaylist",
params:g.yg(l)},a,jBa())}else O8("Connecting without params"),this.g.connect({},a,jBa());QCa(this)};
g.h.dispose=function(){this.ka()||(this.T("beforeDispose"),P8(this,3));N8.ba.dispose.call(this)};
g.h.V=function(){Q8(this);S8(this);R8(this);g.VD(this.H);this.H=window.NaN;g.VD(this.I);this.I=window.NaN;this.o=null;g.oF(this.R);this.R.length=0;this.g.dispose();N8.ba.V.call(this);this.A=this.D=this.l=this.Za=this.g=null};
g.h.wJ=function(){this.C(2)};
g.h.xQ=function(){O8("Channel opened");this.M&&(this.M=!1,R8(this),this.K=g.TD((0,g.z)(function(){O8("Timing out waiting for a screen.");this.C(1)},this),15E3));
nBa($Ba(this.g),this.Y)};
g.h.uQ=function(){O8("Channel closed");(0,window.isNaN)(this.B)?c7(!0):c7();this.dispose()};
g.h.vQ=function(a){c7();(0,window.isNaN)(this.F())?(O8("Channel error: "+a+" without reconnection"),this.dispose()):(this.M=!0,O8("Channel error: "+a+" with reconnection in "+this.F()+" ms"),P8(this,2))};
g.h.wQ=function(a){a.params?O8("Received: action="+a.action+", params="+g.yg(a.params)):O8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Uw(a.params.devices);this.l=(0,g.G)(a,function(a){return new R6(a)});
a=!!g.La(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
TCa(this,a);break;case "loungeScreenDisconnected":g.Va(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
TCa(this,!1);break;case "remoteConnected":var b=new R6(g.Uw(a.params.device));g.La(this.l,function(a){return b?a.id==b.id:!1})||g.Sa(this.l,b);
break;case "remoteDisconnected":b=new R6(g.Uw(a.params.device));g.Va(this.l,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":VCa(this,a);break;case "nowPlaying":XCa(this,a);break;case "onStateChange":WCa(this,a);break;case "onAdStateChange":YCa(this,a);break;case "onVolumeChanged":ZCa(this,a);break;case "onSubtitlesTrackChanged":UCa(this,a);break;case "nowAutoplaying":$Ca(this,a);break;case "autoplayDismissed":this.T("autoplayDismissed");break;case "autoplayUpNext":this.D=a.params.videoId||null;this.T("autoplayUpNext",this.D);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.T("autoplayModeChange",this.A);"DISABLED"==this.A&&this.T("autoplayDismissed");break;case "onHasPreviousNextChanged":aDa(this,a);break;case "requestAssistedSignIn":this.T("assistedSignInRequested",a.params.authCode);break;default:O8("Unrecognized action: "+a.action)}};
g.h.ZU=function(){if(this.o){var a=this.o;this.o=null;this.Za.videoId!=a&&T8(this,"getNowPlaying")}};
N8.prototype.subscribe=N8.prototype.subscribe;N8.prototype.unsubscribeByKey=N8.prototype.Nd;N8.prototype.ga=function(){var a=3;this.ka()||(a=0,(0,window.isNaN)(this.F())?L7(this.g)&&(0,window.isNaN)(this.B)&&(a=1):a=2);return a};
N8.prototype.getProxyState=N8.prototype.ga;N8.prototype.C=function(a){O8("Disconnecting with "+a);Q8(this);this.T("beforeDisconnect",a);1==a&&c7();aCa(this.g,a);this.dispose()};
N8.prototype.disconnect=N8.prototype.C;N8.prototype.fa=function(){var a=this.Za;this.o&&(a=this.Za.clone(),D8(a,this.o,a.index));return E8(a)};
N8.prototype.getPlayerContextData=N8.prototype.fa;
N8.prototype.na=function(a){var b=new y8(a);b.videoId&&b.videoId!=this.Za.videoId&&(this.o=b.videoId,g.VD(this.H),this.H=g.TD((0,g.z)(this.ZU,this),5E3));var c=[];this.Za.listId==b.listId&&this.Za.videoId==b.videoId&&this.Za.index==b.index||c.push("remoteQueueChange");this.Za.g==b.g&&this.Za.volume==b.volume&&this.Za.muted==b.muted&&C8(this.Za)==C8(b)&&g.yg(this.Za.l)==g.yg(b.l)||c.push("remotePlayerChange");this.Za.reset(a);(0,g.B)(c,function(a){this.T(a)},this)};
N8.prototype.setPlayerContextData=N8.prototype.na;N8.prototype.X=function(){var a=this.g.C.id,b=g.La(this.l,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
N8.prototype.getOtherConnectedRemoteId=N8.prototype.X;N8.prototype.F=function(){var a=this.g;return a.l.isActive()?a.l.l-(0,g.F)():window.NaN};
N8.prototype.getReconnectTimeout=N8.prototype.F;N8.prototype.Z=function(){return this.A||"UNSUPPORTED"};
N8.prototype.getAutoplayMode=N8.prototype.Z;N8.prototype.ca=function(){return this.D||""};
N8.prototype.getAutoplayVideoId=N8.prototype.ca;N8.prototype.sa=function(){if(!(0,window.isNaN)(this.F())){var a=this.g.l;g.Xt(a.g);a.start()}};
N8.prototype.reconnect=N8.prototype.sa;N8.prototype.ha=function(a,b){T8(this,a,b);SCa(this)};
N8.prototype.sendMessage=N8.prototype.ha;g.A(U8,U7);g.h=U8.prototype;g.h.ie=function(a){return this.dd.$_gs(a)};
g.h.contains=function(a){return!!this.dd.$_c(a)};
g.h.get=function(a){return this.dd.$_g(a)};
g.h.start=function(){this.dd.$_st()};
g.h.add=function(a,b,c){this.dd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.dd.$_r(a,b,c)};
g.h.kq=function(a,b,c,d){this.dd.$_un(a,b,c,d)};
g.h.V=function(){for(var a=0,b=this.l.length;a<b;++a)this.dd.$_ubk(this.l[a]);this.l.length=0;this.dd=null;U8.ba.V.call(this)};
g.h.qW=function(){this.T("screenChange")};
g.h.tS=function(){this.T("onlineScreenChange")};
c8.prototype.$_st=c8.prototype.start;c8.prototype.$_gspc=c8.prototype.rW;c8.prototype.$_gsppc=c8.prototype.bF;c8.prototype.$_c=c8.prototype.contains;c8.prototype.$_g=c8.prototype.get;c8.prototype.$_a=c8.prototype.add;c8.prototype.$_un=c8.prototype.kq;c8.prototype.$_r=c8.prototype.remove;c8.prototype.$_gs=c8.prototype.ie;c8.prototype.$_gos=c8.prototype.aF;c8.prototype.$_s=c8.prototype.subscribe;c8.prototype.$_ubk=c8.prototype.Nd;var V8=null,W8=null,k9=null,$8=[];g.p(l9,g.M);g.h=l9.prototype;
g.h.V=function(){g.M.prototype.V.call(this);this.A.stop();this.B.stop();this.J.stop();this.M();this.g.unsubscribe("proxyStateChange",this.JC,this);this.g.unsubscribe("remotePlayerChange",this.pm,this);this.g.unsubscribe("remoteQueueChange",this.up,this);this.g.unsubscribe("autoplayUpNext",this.hC,this);this.g.unsubscribe("previousNextChange",this.GC,this);this.g.unsubscribe("nowAutoplaying",this.yC,this);this.g.unsubscribe("autoplayDismissed",this.gC,this);this.g=this.F=null};
g.h.iB=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(o9(this)){if(!H8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":H8(this.g).kb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.Hj(c[0],c[1]);break;case "control_subtitles_set_track":p9(this,c[0]);break;case "control_set_audio_track":c=c[0],o9(this)&&this.g.Uv(this.l.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.l.getCurrentTime();q9(this,0==c?void 0:c);break;case "control_seek":q9(this,c[0]);break;case "control_subtitles_set_track":p9(this,c[0]);break;case "control_set_audio_track":c=c[0],o9(this)&&this.g.Uv(this.l.getVideoData(1).videoId,c)}};
g.h.rQ=function(a){this.J.rJ(a)};
g.h.UV=function(a){this.iB("control_subtitles_set_track",g.Wb(a)?null:a)};
g.h.oE=function(){var a=this.l.xc("captions","track");g.Wb(a)||p9(this,a)};
g.h.wC=function(a){if(o9(this)){this.g.unsubscribe("remotePlayerChange",this.pm,this);var b=Math.round(a.volume);a=!!a.muted;var c=H8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.K.start();this.g.subscribe("remotePlayerChange",this.pm,this)}};
g.h.NR=function(){g.Wb(this.C)||mDa(this,this.C);this.D=!1};
g.h.JC=function(a,b){this.B.stop();2==b&&this.lE()};
g.h.pm=function(){if(o9(this)){this.A.stop();var a=H8(this.g);switch(a.g){case 1081:case 1:n9(this,new g.vP(8));this.kE();break;case 1085:case 3:n9(this,new g.vP(9));break;case 1083:case 0:n9(this,new g.vP(2));this.I.stop();m9(this,this.l.getVideoData().lengthSeconds);break;case 1084:n9(this,new g.vP(4));break;case 2:n9(this,new g.vP(4));m9(this,C8(a));break;case -1:n9(this,new g.vP(64));break;case -1E3:n9(this,new g.vP(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=
H8(this.g).l;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,mDa(this,a));a=H8(this.g);-1==a.volume||Math.round(this.l.getVolume())==a.volume&&this.l.isMuted()==a.muted||this.K.isActive()||this.LE()}else lDa(this)};
g.h.GC=function(){this.l.T("mdxpreviousnextchange")};
g.h.up=function(){o9(this)||lDa(this)};
g.h.CI=function(){this.g.gy()};
g.h.hC=function(a){a&&(a=g.jE("/watch_queue_ajax",{method:"GET",Xc:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.z)(this.aU,this)}))&&(this.M=(0,g.z)(a.abort,a))};
g.h.aU=function(a,b){var c=new g.mO({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.l.T("mdxautoplayupnext",c)};
g.h.yC=function(a){(0,window.isNaN)(a)||this.l.T("mdxnowautoplaying",a)};
g.h.gC=function(){this.l.T("mdxautoplaycanceled")};
g.h.qO=function(a,b){-1==H8(this.g).g?q9(this,a):b&&this.g.YE(a)};
g.h.LE=function(){if(o9(this)){var a=H8(this.g);this.o.Ea(this.R);a.muted?this.l.mute():this.l.dg();this.l.setVolume(a.volume);this.R=this.o.O(this.l,"onVolumeChange",this.wC)}};
g.h.kE=function(){this.A.stop();if(!this.g.ka()){var a=H8(this.g);a.kb()&&n9(this,new g.vP(8));m9(this,C8(a));this.A.start()}};
g.h.lE=function(){this.B.stop();this.A.stop();var a=this.g.A.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p(r9,g.W);r9.prototype.B=function(a){oDa(this,a.state)};g.p(s9,g.$Z);s9.prototype.J=function(){var a=this.o.xc("remote","receivers");a&&1<a.length&&!this.o.xc("remote","quickCast")?(this.H=g.kb(a,this.C,this),g.a_(this,(0,g.G)(a,this.C)),a=this.o.xc("remote","currentReceiver"),this.vf(this.C(a)),this.enable(!0)):this.enable(!1)};
s9.prototype.C=function(a){return a.key};
s9.prototype.uf=function(a){return"cast-selector-receiver"==a?"Cast...":this.H[a].name};
s9.prototype.sd=function(a){g.$Z.prototype.sd.call(this,a);this.o.Jd("remote","currentReceiver",this.H[a]);this.B.Pb()};g.p(t9,g.wV);g.h=t9.prototype;g.h.create=function(){fDa(g.CM(g.Y(this.g)));this.C.push(g.QF("yt-remote-before-disconnect",this.nQ,this));this.C.push(g.QF("yt-remote-connection-change",this.cT,this));this.C.push(g.QF("yt-remote-receiver-availability-change",this.HC,this));this.C.push(g.QF("yt-remote-auto-connect",this.aT,this));this.C.push(g.QF("yt-remote-receiver-resumed",this.ZS,this));this.HC()};
g.h.load=function(){this.g.Xt();g.wV.prototype.load.call(this);this.B=new l9(this,this.g,this.l);var a=(a=kDa())?a.currentTime:0;var b=j9()?new G8(e9(),void 0):null;0==a&&b&&(a=C8(H8(b)));0!=a&&(this.H=a||0,this.g.T("progresssync",a,void 0));nDa(this,this.D,this.D);g.v0(this.g.app,6)};
g.h.unload=function(){this.g.T("mdxautoplaycanceled");this.A=this.o;g.af(this.B,this.l);this.l=this.B=null;g.wV.prototype.unload.call(this);g.v0(this.g.app,5)};
g.h.V=function(){g.RF(this.C);g.wV.prototype.V.call(this)};
g.h.Yl=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.iB.apply(this.B,[a].concat(g.pa(c)))};
g.h.nJ=function(){return this.loaded?this.B.suggestion:null};
g.h.Sf=function(){return this.l?H8(this.l).Sf:!1};
g.h.hasNext=function(){return this.l?H8(this.l).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.eO=function(){var a=H8(this.l),b=this.g.getVideoData();return{allowSeeking:this.g.ed(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.C?a.A+A8(a):a.A,isPeggedToLive:1>=(a.C?a.o+A8(a):a.o)-this.getCurrentTime(),loaded:a.I,seekableEnd:a.C?a.o+A8(a):a.o,seekableStart:0<a.B?a.B+A8(a):a.B}};
g.h.fO=function(){this.l&&this.l.WE()};
g.h.gO=function(){this.l&&this.l.XE()};
g.h.nQ=function(a){1==a&&(this.I=this.l?H8(this.l):null)};
g.h.cT=function(){var a=j9()?new G8(e9(),void 0):null;if(a){var b=this.A;this.loaded&&this.unload();this.l=a;this.I=null;b.key!=this.o.key&&(this.A=b,this.load())}else g.$e(this.l),this.l=null,this.loaded&&(this.unload(),(a=this.I)&&a.videoId==this.g.getVideoData().videoId&&this.g.MA(a.videoId,C8(a)));this.g.T("videodatachange","newdata",this.g.getVideoData(),3)};
g.h.HC=function(){this.F=[this.o].concat(hDa());var a=f9()||this.o;u9(this,a);this.g.va("onMdxReceiversChange")};
g.h.aT=function(){var a=f9();u9(this,a)};
g.h.ZS=function(){this.A=f9()};
g.h.dO=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?w8():u9(this,b)),this.loaded?this.A:this.o;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&w8(),!0):!1}};
g.h.hO=function(){L8(this.l,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Gc=function(){return!1};g.mY.remote=t9;})(_yt_player);
